# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAllItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='num')),
                ('item', models.CharField(db_column='item', max_length=500)),
                ('status', models.CharField(db_column='status', max_length=10)),
            ],
            options={
                'db_table': 'riskmodel_model_all_items',
            },
        ),
        migrations.CreateModel(
            name='ModelDetailsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_num', models.CharField(db_column='item_num', max_length=30)),
                ('item_detail_num', models.CharField(db_column='item_detail_num', max_length=30)),
                ('item_content', models.CharField(db_column='item_content', max_length=300)),
                ('config_date', models.CharField(db_column='config_date', max_length=20)),
                ('config_basic', models.CharField(db_column='config_basic', max_length=20)),
                ('config_min', models.CharField(db_column='config_min', max_length=20)),
                ('config_max', models.CharField(db_column='config_max', max_length=20)),
                ('item_level', models.CharField(db_column='item_level', max_length=30)),
                ('score', models.CharField(db_column='score', max_length=20)),
                ('status', models.CharField(db_column='status', max_length=10)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'riskmodel_model_details_config',
            },
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_column='model_name', max_length=50)),
                ('relation_nums', models.CharField(db_column='relation_nums', max_length=500)),
                ('auth', models.CharField(db_column='auth', max_length=50)),
                ('status', models.CharField(db_column='status', max_length=10)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'riskmodel_rigister_model',
            },
        ),
    ]
